//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectRC
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class dostawa
    {
        public int id_dostawa { get; set; }
        public string nazwa { get; set; }
        public Nullable<decimal> cena { get; set; }
    }
}
