//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectRC
{
    using System;
    using System.Collections.ObjectModel;

    /// <summary>
    /// Klasa obietu klienci
    /// </summary>
    public partial class klienci
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public klienci()
        {
            this.zamowienia = new ObservableCollection<zamowienia>();
        }

        /// <summary>
        /// Property id_klienci
        /// </summary>
        public int id_klienci { get; set; }

        /// <summary>
        /// Property imie
        /// </summary>
        public string imie { get; set; }

        /// <summary>
        /// Property nazwisko
        /// </summary>
        public string nazwisko { get; set; }

        /// <summary>
        /// Property nr_tel
        /// </summary>
        public Nullable<int> nr_tel { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableCollection<zamowienia> zamowienia { get; set; }
    }
}
