//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectRC
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class zamowienia
    {
        public int id_zamowienia { get; set; }
        public Nullable<int> id_produktu { get; set; }
        public Nullable<int> id_klienta { get; set; }
        public Nullable<decimal> rabat { get; set; }
        public Nullable<System.DateTime> data_zakupu { get; set; }
    
        public virtual klienci klienci { get; set; }
        public virtual produkty produkty { get; set; }
    }
}
